---
title: "Graph_New"
author: "Luisa Jansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load Packages

```{r Pakete, message = FALSE}
library(remotes)
library(rlang)
library(ggpattern)
library(dplyr)
library(ggplot2)
library(readxl)
library(data.table)
library(tibble)
library(tidyr)
library(stringr)
library(wesanderson)
```

#### Load Data

```{r}
wholedata <- read_excel("C:/Users/luisa/Documents/Arbeit/Nele/Review Self-Efficacy/Grafik/Aktualisierter Versuch/Review_data_all_packages.xlsx")

data <- wholedata[, c("cause_variables_new", "cause_variables_theory", "cause_variables_theory_other")]

data <- rowid_to_column(data, "ID")
```

#### Test 1
Split "cause_variables_theory_other" and "cause_variables_theory". 
Try to loop over all rows and "cause_variables_theory" columns to replace "other" values. 
Problem: function does not work
```{r}
max(lengths(strsplit(as.character(data$cause_variables_theory_other), '; '))) # 8
setDT(data)[, paste0("cause_variables_theory_other", 1:8) := tstrsplit(data$cause_variables_theory_other, "; ")]

max(lengths(strsplit(as.character(data$cause_variables_theory), '; '))) # 9
data1 <- setDT(data)[, paste0("cause_variables_theory", 1:9) := tstrsplit(data$cause_variables_theory, "; ")]

i <- 0
j <- 0
k <- 0
for (i in 1:186) {k <- 0;
  for(j in 13:21) {
  if(grepl("other", data1[i, ..j]) == TRUE) {
      data1[i,j] <- data1[i,k+5]; k <- k + 1; print(k)}}}

```


#### Test 2
Split columns with separate function
Problem: No inclusion of "cause_variables_theory_other"
``` {r}
data_test2 <- separate_rows(data, cause_variables_new, cause_variables_theory, sep = ";")

# Delete whitespaces in beginning of columns
data_test2 <- data_test2 %>% mutate(cause_variables_new = trimws(cause_variables_new))
data_test2 <- data_test2 %>% mutate(cause_variables_theory = trimws(cause_variables_theory))

```